# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WaktaverseMusic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher', '~> 7.0'
  pod 'Alamofire'
  pod 'SwiftLint'
  
  
  pod 'LGSideMenuController'
  
  # Pods for WaktaverseMusic

  target 'WaktaverseMusicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WaktaverseMusicUITests' do
    # Pods for testing
  end

end
